#!/bin/bash

DOMAINS_FILE="domains.txt"
OUTPUT_FILE="Caddyfile"

# Check domains.txt
if [[ ! -f "$DOMAINS_FILE" ]]; then
  echo "❌ '$DOMAINS_FILE' not found!"
  exit 1
fi

echo "📝 Generating Caddyfile..."

echo "# Auto-generated by generate_caddyfile.sh" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

while IFS= read -r line || [[ -n "$line" ]]; do
  DOMAIN=$(echo "$line" | awk '{print $1}')
  PORT=$(echo "$line" | awk '{print $2}')

  if [[ -n "$DOMAIN" && -n "$PORT" ]]; then
    cat <<EOF >> "$OUTPUT_FILE"
$DOMAIN {
  reverse_proxy 127.0.0.1:$PORT
}
EOF
    echo "" >> "$OUTPUT_FILE"
  fi
done < "$DOMAINS_FILE"

echo "✅ Caddyfile generated at $OUTPUT_FILE."
