volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    # # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (slow releases) or #edge (rolling release) or a specific release like #1.21.0
    #   context: https://github.com/FreshRSS/FreshRSS.git#latest
    #   dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
      - 7005:80
    logging:
      options:
        max-size: 10m
    volumes:
      - ../data/freshrss/data:/var/www/FreshRSS/data
      - ../data/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: "Asia/Kolkata"
      CRON_MIN: '3,33'
      # TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
    # # Optional healthcheck section:
    # healthcheck:
    #   test: ["CMD", "cli/health.php"]
    #   timeout: 10s
    #   start_period: 60s
    #   start_interval: 11s
    #   interval: 75s
    #   retries: 3
